import { Property } from "../lib/properties";

export const SAMPLE_PROPERTIES: Property[] = [
  {
    id: 'sample-1',
    userId: 'sample',
    title: 'Modern Downtown Apartment',
    type: 'Apartment',
    guests: 4,
    bedrooms: 2,
    bathrooms: 2,
    location: {
      address: '123 Main Street',
      city: 'New York',
      country: 'United States',
    },
    amenities: ['WiFi', 'Kitchen', 'AC', 'TV'],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
    pricing: {
      perNight: 150,
      cleaningFee: 50,
    },
    description: 'Beautiful modern apartment in the heart of downtown',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'sample-2',
    userId: 'sample',
    title: 'Cozy Beach House',
    type: 'House',
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    location: {
      address: '456 Ocean Drive',
      city: 'Miami',
      country: 'United States',
    },
    amenities: ['WiFi', 'Pool', 'Parking', 'Kitchen'],
    images: ['https://images.unsplash.com/photo-1499916078039-922301b0eb9b?w=800&q=80'],
    pricing: {
      perNight: 220,
      cleaningFee: 75,
    },
    description: 'Stunning beach house with ocean views',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'sample-3',
    userId: 'sample',
    title: 'Luxury Villa with Pool',
    type: 'Villa',
    guests: 8,
    bedrooms: 4,
    bathrooms: 3,
    location: {
      address: '789 Paradise Lane',
      city: 'Los Angeles',
      country: 'United States',
    },
    amenities: ['WiFi', 'Pool', 'Gym', 'Parking', 'AC'],
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'],
    pricing: {
      perNight: 350,
      cleaningFee: 100,
    },
    description: 'Luxurious villa with stunning mountain views',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'sample-4',
    userId: 'sample',
    title: 'Downtown Loft Studio',
    type: 'Apartment',
    guests: 2,
    bedrooms: 1,
    bathrooms: 1,
    location: {
      address: '321 Art District',
      city: 'San Francisco',
      country: 'United States',
    },
    amenities: ['WiFi', 'Kitchen', 'Washer'],
    images: ['https://images.unsplash.com/photo-1502672260066-6bc44a9f0e32?w=800&q=80'],
    pricing: {
      perNight: 95,
      cleaningFee: 30,
    },
    description: 'Charming loft in trendy neighborhood',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'sample-5',
    userId: 'sample',
    title: 'Mountain Cabin Retreat',
    type: 'House',
    guests: 5,
    bedrooms: 2,
    bathrooms: 2,
    location: {
      address: '555 Pine Forest Road',
      city: 'Aspen',
      country: 'United States',
    },
    amenities: ['WiFi', 'Parking', 'Kitchen', 'TV'],
    images: ['https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&q=80'],
    pricing: {
      perNight: 180,
      cleaningFee: 60,
    },
    description: 'Peaceful mountain getaway with scenic views',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
  },
  {
    id: 'sample-6',
    userId: 'sample',
    title: 'Urban Chic Condo',
    type: 'Condo',
    guests: 3,
    bedrooms: 1,
    bathrooms: 1,
    location: {
      address: '888 Downtown Plaza',
      city: 'Chicago',
      country: 'United States',
    },
    amenities: ['WiFi', 'AC', 'TV', 'Gym'],
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80'],
    pricing: {
      perNight: 120,
      cleaningFee: 40,
    },
    description: 'Stylish condo in prime location',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: 'active',
  },
];